### ISSUE TITLE
TodoList 2023년 12월 21일

### ISSUE THREAD

**Issue by fkdl0048** [fkdl0048/ToDo#547]
# TodoList

1. 진행상황은 Comment로 남길 것
2. 모든 진행 상황은 정직하고 솔직하게 기재
3. 매 주 일요일에 2주 계획 만들기
4. 매일 하루에 대한 짧은 회고

## Todo  

- [x] https://github.com/BRIDGE-DEV/BRIDGE_BookClub/issues/72

## Books

- [x] https://github.com/fkdl0048/BookReview/issues/195
- [x] https://github.com/fkdl0048/BookReview/issues/196

**Comment by fkdl0048** [comment]
- 팀 프로젝트 공지사항 전달
- 스터디 3종 업데이트

**Comment by fkdl0048** [comment]
- 아카데미 컨퍼런스 참여 메일 회신

**Comment by fkdl0048** [comment]
- 스케줄 정리
